PR
federicofranco97/ProyectoCine pull request #32
Opened 2019-08-27 21:52 UTC by federicofranco97

Pull request con todo lo pedido, comentado de codigo, casos de prueba y la identacion arreglada. 
Cualquier cosa estamos en contacto!

2019-08-27 21:58 UTC, didierrenardub commented
Recibido, lo veré en un rato.

Saludos,
Didier

El mar., 27 ago. 2019 a las 18:52, Federico Franco (<
notifications@github.com>) escribió:

> Pull request con todo lo pedido, comentado de codigo, casos de prueba y la
> identacion arreglada.
> Cualquier cosa estamos en contacto!
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/federicofranco97/ProyectoCine/pull/32
> Commit Summary
>
>    - clean menu
>    - works in intelliJ settings
>    - started to define mappers
>    - modifs to layout and controller
>    - finished current dtos mapping
>    - modif to sql conection and added method in mapping
>    - Added embedded clock to navbar and more
>    - implemented ger user by id with full trajectory
>    - implemented error / result logging
>    - Changes to loggings and started to format dashboard
>    - Merge pull request #5 from federicofranco97/fede
>    - initial commit rejunte
>    - Merge pull request #7 from federicofranco97/feature/gitignore
>    - modif sql driver
>    - Added Data methods
>    - removed bin folder
>    - Added data methods
>    - Modif get all clients
>    - Added validacion de rol de empleado
>    - modificaciones en html de la vista menu
>    - Hoja de estilo de la vista menu añadida
>    - Controller de la vista menu agregado
>    - Started admin main view
>    - Modifs to the employees managment
>    - Correccion en menu controller
>    - Hoja de estilo de menu añadida en layout
>    - Modificacion en vista menu de html
>    - changes to employee view
>    - implemented ban employee
>    - Added view edit controller, missing overwrite data in profile
>    - persist employee update in db
>    - Added test folder
>    - Merge branch 'rejunte' into adminview
>    - removed unused imports
>    - Merge branch 'rejunte' into menu
>    - Started to implement tickets view
>    - Separation bt active tickets and all tickets
>    - added functions to tickets
>    - supresion de linea innecesaria en controller del menu y theme
>    agregado en el html
>    - initial commit login html
>    - add cuerpo login
>    - add coments html
>    - add css
>    - add js file and function
>    - add comments js
>    - add controllers
>    - modified function IsEmployeeAlowed from client service
>    - Panel de admin añadido a vista menu
>    - add functions, comments and controller
>    - fix mistakes
>    - dto
>    - add static employee
>    - Merge pull request #9 from federicofranco97/login
>    - Merge branch 'rejunte' into adminview
>    - Merge pull request #10 from federicofranco97/adminview
>    - correccion de estilo y modifcacion controller en vista menu
>    - Merge branch 'rejunte' into menu
>    - Merge pull request #11 from federicofranco97/menu
>    - Linked login with menu
>    - fixed navbar, clear current user when logout, stated mappings
>    - Merge pull request #12 from federicofranco97/rejunte
>    - addded metodo para validar si hay un usuario en current
>    - Merge pull request #14 from federicofranco97/rejunte
>    - Merge pull request #16 from federicofranco97/rejunte
>    - modif to view proportions
>    - added page to create tickets and sp
>    - added required to fields
>    - added modif to controller
>    - added vista error
>    - Merge pull request #17 from federicofranco97/adminview
>    - Merge pull request #18 from federicofranco97/rejunte
>    - add model and view object
>    - Added ticket error managment
>    - started to implement client manager
>    - corrected style for empl edit
>    - Added admin main carrousel
>    - add all data tests
>    - add test and implements mapping films function
>    - Changed date to string
>    - Merge pull request #20 from federicofranco97/rejunte
>    - Merge branch 'rejunte' into adminview
>    - changes
>    - Merge branch 'login' of
>    https://github.com/federicofranco97/ProyectoCine into login
>    - modif super with string date
>    - Merge pull request #21 from federicofranco97/rejunte
>    - Merge branch 'rejunte' into adminview
>    - more changes
>    - Merge branch 'login' of
>    https://github.com/federicofranco97/ProyectoCine into login
>    - add tests clientService and implements mapping function
>    - add more tests from clientService
>    - add test GetEmployeeCategory
>    - add test getAllEmployees codRol != 5
>    - add tests banEmployee
>    - nothing
>    - add tests clientService
>    - modif data type to boolean in post new client
>    - Merge pull request #23 from federicofranco97/rejunte
>    - Merge pull request #24 from federicofranco97/rejunte
>    - vista de retiro de entradas creada, html y css
>    - Modif client service datatype
>    - controller agregado a vista retiro entradas
>    - Merge branch 'rejunte' into adminview
>    - Merge pull request #25 from federicofranco97/rejunte
>    - Merge pull request #26 from federicofranco97/rejunte
>    - cierres de tag, etc en vista retiro
>    - modif to change
>    - Added content to login error
>    - modif viewsize of table
>    - Merge pull request #27 from federicofranco97/login
>    - Correccion en estilo de vista y metodo agregado en controller
>    - Merge pull request #28 from federicofranco97/rejunte
>    - Merge branch 'retiroe' of
>    https://github.com/federicofranco97/ProyectoCine into retiroe
>    - Librerias para el proyecto
>    - modif to manag emp
>    - Merge pull request #29 from federicofranco97/retiroe
>    - Merge branch 'adminview' into rejunte
>    - add test updateEmployee
>    - add test getALLTICKETS client service class
>    - add test getAllTickets from clientService
>    - add documentation
>    - add test IsActiveUser from client service
>    - add test createTicket from client service
>    - add testDTOEmployee from mapping tool
>    - add test booking mapping
>    - add testig from mapping tool
>    - addlast tests from mapping tool
>    - add changes test from mapping tool class
>    - more changes
>    - Merge pull request #31 from federicofranco97/login
>
> File Changes
>
>    - *M* .classpath
>    <https://github.com/federicofranco97/ProyectoCine/pull/32/files#diff-0>
>    (2)
>    - *A* .gitignore
>    <https://github.com/federicofranco97/ProyectoCine/pull/32/files#diff-1>
>    (3)
>    - *A* .idea/libraries/sqljdbc42.xml
>    <https://github.com/federicofranco97/ProyectoCine/pull/32/files#diff-2>
>    (9)
>    - *A* .idea/misc.xml
>    <https://github.com/federicofranco97/ProyectoCine/pull/32/files#diff-3>
>    (6)
>    - *A* .idea/modules.xml
>    <https://github.com/federicofranco97/ProyectoCine/pull/32/files#diff-4>
>    (8)
>    - *A* .idea/vcs.xml
>    <https://github.com/federicofranco97/ProyectoCine/pull/32/files#diff-5>
>    (6)
>    - *D* bin/ar/edu/ub/progiii/mvc/MvcApplication.class
>    <https://github.com/federicofranco97/ProyectoCine/pull/32/files#diff-6>
>    (0)
>    - *D* bin/ar/edu/ub/progiii/mvc/controller/WithdrawController.class
>    <https://github.com/federicofranco97/ProyectoCine/pull/32/files#diff-7>
>    (0)
>    - *D* bin/ar/edu/ub/progiii/mvc/controller/blank.class
>    <https://github.com/federicofranco97/ProyectoCine/pull/32/files#diff-8>
>    (0)
>    - *D* bin/ar/edu/ub/progiii/mvc/dto/BookingDTO.class
>    <https://github.com/federicofranco97/ProyectoCine/pull/32/files#diff-9>
>    (0)
>    - *D* bin/ar/edu/ub/progiii/mvc/dto/ClientDTO.class
>    <https://github.com/federicofranco97/ProyectoCine/pull/32/files#diff-10>
>    (0)
>    - *D* bin/ar/edu/ub/progiii/mvc/dto/EmployeeDTO.class
>    <https://github.com/federicofranco97/ProyectoCine/pull/32/files#diff-11>
>    (0)
>    - *D* bin/ar/edu/ub/progiii/mvc/dto/OnSiteBookingDTO.class
>    <https://github.com/federicofranco97/ProyectoCine/pull/32/files#diff-12>
>    (0)
>    - *D* bin/ar/edu/ub/progiii/mvc/dto/OnlineBookingDTO.class
>    <https://github.com/federicofranco97/ProyectoCine/pull/32/files#diff-13>
>    (0)
>    - *D* bin/ar/edu/ub/progiii/mvc/dto/PersonDTO.class
>    <https://gi [...]

2019-08-27 22:02 UTC, federicofranco97 commented
Si no hay ningun apuro, entendemos que es un pull enorme y que va a llevar tiempo! Gracias por la ayuda! 
Saludos.

2019-08-28 02:43 UTC, didierrenardub requested changes
Muy bien por incluir los tests! Creo que si no fuera por problemas de formateo no habría una gran cantidad de feedback. Por otro lado, la longitud del PR hizo difícil su review y se me pueden llegar a haber pasado cosas.

Por favor, intenten hacer PRs más chicos en el futuro para que puedan tener un mejor feedback de mi parte (y más rápido).

Saludos!

2019-08-28 02:43 UTC, didierrenardub commented on .classpath
> +	<classpathentry kind="lib" path="C:/Users/Administrator/Desktop/Facu/springboot-workspace/ProyectoCine/libs/junit-jupiter-5.5.1.jar"/>
No para cambiarlo ahora, pero a los fines del conocimiento, busquen a ver si se pueden hacer estar rutas relativas.
Esto pinta que es el proyecto de Eclipse o el IDE de Spring.

2019-08-28 02:43 UTC, didierrenardub commented on .gitignore
> +.idea
Recién ahora lo veo, pero esto puede llegar a ser, @federicofranco97, lo que te traía problemas con IntelliJ. Si te vuelve a pasar, habría que explorar la posibilidad de que no todo lo que está dentro de .idea tenga que ira .gitignore.

Yo pienso que sí y que quien tiene toda la información que IntelliJ necesita está en el .iml en el root, pero bueno, para tenerlo en la mira.

2019-08-28 02:43 UTC, didierrenardub commented on .idea/libraries/sqljdbc42.xml
> +<component name="libraryTable">
No estoy seguro de que esto tenga que ir a .gitignore, pero lo llamativo es que la carpeta .idea está ignorada con lo cual este archivo no debería haber estado subido.

Puede que se haya ignorado la carpeta luego de la creación y subida a Git y por eso aparece aquí.

Hagan la prueba de cerrar el IDE (IntelliJ), sacar este archivo y ver si todo sigue funcionando como debería. En base a los resultados determinaremos si puede eliminarse del repo o no.

Es muy importante mantener el repositorio con la menor cantidad de extras innecesarios posible.

2019-08-28 02:43 UTC, didierrenardub commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Lo mismo con este archivo. Para no spammear tanto comentario, apliquen lo que dije antes a todo lo que esté dentro de .idea.

2019-08-28 02:43 UTC, didierrenardub commented on codeSqlServer/Conection.java
>  			ResultSet rst = stm.executeQuery("select * from dbo.Cliente");
Las queries deberían tener su propia clase (o clases, depende de cómo se diseñe la arquitectura) para un mejor mantenimiento y depuración.

Por otro lado, deduzco que quizás esto es código de prueba, que de confirmarse, debería estar en el sector de Unit Tests y no aquí.

2019-08-28 02:43 UTC, didierrenardub commented on codeSqlServer/Conection.java
> +				System.out.println("nombre: " + rst.getString("NombreCompleto"));
Definir constantes para los strings, y con más razón aún si hacen referencia a la estructura de datos (en este caso, una columna de una tabla).

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/css/Menu.css
> +#menuTable {
Respecto del archivo anterior en el diff (al menos aquí yo veo como anterior resources/static/css/ManagerEmp.css), hay inconsistencia en la posición de las llaves que delimitan scopes. En el archivo anterior siempre en una línea nueva, aquí siempre al final de la línea.

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/css/Tickets.css
> +.CardContainer
Aquí veo más inconsistencias respecto de las llaves en línea nueva / al final de la línea entre:
resources/static/css/RetiroEntradas.css
y el archivo actual, resources/static/css/Tickets.css

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/css/Tickets.css
> +.CardContainer
Además, no se respeta la nomenclatura de las clases css; esta está en CamelCase mientras que las otras están en snake-case. Ejemplos que veo en CamelCase:
CardContainer
thDesign (y notar que no es consistente el CamelCase siendo que este segundo ejemplo comienza con minúscula)
data-form
table-style
tableDesign

Por favor rever esto en todos los css.

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/css/RetiroEntradas.css
> +.center{
El nombre del archivo está en castellano pero el código en su interior está en Inglés. Si todo el código va en inglés, también tienen que ir los nombres de los archivos puesto que en general se asocia el nombre del archivo a su contenido o parte de él.

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/css/login.css
> +#title{
Habría que evitar nombres tan genéricos para los ids, porque pueden traer problemas. Sería mejor algo así como:
login-screen-title
Por dar un ejemplo.

Otra cosa, el nombre del archivo css arranca con minúscula en este caso pero en el resto de los que vi, o varios de ellos, arrancan en mayúsculas. Hay que hacerlos consistentes.

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/js/Alivio.js
>  //Verifico que el valor ingresado para retirar sea valido, e igual o mehor que el total
Está mal escrito "mehor"

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/js/Alivio.js
> +        console.log(AmountSelected);
No está bien commitear console logs sin que sea posible activarlos o desactivarlos con alguna variable de control para debug.

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/js/Alivio.js
> +    if(AmountSelected < 1  || AmountSelected>TotalSales || AmountSelected===null || Number.isNaN(AmountSelected)){
Se dejan espacios entre:
`AmountSelected < 1`
Pero no entre
`AmountSelected>TotalSales`
ni entre
`AmountSelected===null`

Adicionalmente, hay un doble espacio entre 1 y ||.

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/js/Alivio.js
>  var inAmount=document.getElementById("amountTaken");
Inconsistencia en los nombres de las variables: las definidas más arriba arrancan todas con mayúscula, mientras que estas dos arrancan con minúscula.

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/js/Alivio.js
>  //End Variable declaration
Comentario en inglés cuando otros comentarios están en castellano.

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/js/Alivio.js
> +    var TotalSales= parseInt(inTotal.value);
Inconsistencia en los espacios; en:
`var AmountSelected=parseInt(inAmount.value);`
No se deja espacio en la asignación, sin embargo:
`var TotalSales= parseInt(inTotal.value);`

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/js/Alivio.js
>  function VerifyWithdraw(){
Por la naturaleza de esta validación, debería ser sometida a Unit Tests. Obviamente aún me falta revisar la mayor parte de este PR, pero en caso de no hallarlos, van a tener que agregarlos.

Para poder hacer el Unit Test van a tener que definir una función que reciba los parámetros necesarios para hacer la verificación que tiene que hacer, y luego invocar esa función dentro de esta.

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/js/Alivio.js
>  function AskForID(){
Mismo caso aquí; hay demasiada interacción y procesamiento como para no hacer Unit Tests de esto. Va a haber que refactorear para que sea testeable, abstrayendo las formas de entrada y salida de datos.

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/js/Alivio.js
> -var AmountSelected=parseInt(document.getElementById("amountTaken").value);
Los strings que se utilicen más de una vez (como por ejemplo amountTaken) deben ser definidos en constantes.

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/js/Alivio.js
> +        var TotalSales= parseInt(inTotal.value);
Nuevamente, inconsistencia en los espacios en la asignación.

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/js/Alivio.js
>          swal("Ingrese su id de Supervisor:", {
Inconsistencia en el símbolo utilizado para los strings; en ocasiones se usan comillas dobles y en ocasiones comillas simples.

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/js/ManagerClie.js
> +//move to edit client information
Comentarios en inglés cuando en otros lugares hay comentarios en español. Para no seguir spammeando no voy a seguir señalando este problema; por favor corrijan en todos los lugares según sea necesario. Lo importante es que se mantenga siempre de la misma manera.

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/js/ManagerClie.js
> +    var id=Component.parentNode.className;
Evitar el uso de "id" como nombre de variable. En varios lenguajes (Objective-C, Python, Swift, que recuerde ahora) "id" es una palabra reservada para distintos usos.
En este caso, asumo que podría ser renombrada a clientId.

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/js/ManagerClie.js
> +    var id=Component.parentNode.className;
Mismo caso con la variable "id".

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/js/ManagerClie.js
> +
Espacio innecesario.

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/js/ManagerEmp.js
> +    var id=Component.parentNode.className;
Con este dejo de spammear, pero revisen lo de las variables "id".

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/js/ManagerEmp.js
> +//move to edit employee information
Veo que este archivo replica lo mismo que el anterior (resources/static/js/ManagerClie.js). Habría que definir funciones más genéricas y reutilizar en lugar de hacer copy-paste.

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/js/RetiroEntradas.js
> +    alert(id);
En lugar de estas dos líneas, podría ser, directamente:
`alert(inputCode.value);`

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/js/ManagerClie.js
> +//Ban client
Falta documentar el método.

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/js/ManagerClie.js
> +function ReturnToMenuClient(){
Falta documentar el método.

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/js/ManagerEmp.js
> +//Ban employee
Documentación insuficiente.

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/js/ManagerEmp.js
> +function ReturnToMenu(){
Falta documentar.

2019-08-28 02:43 UTC, didierrenardub commented on resources/static/js/RetiroEntradas.js
> +function BringBooking(){
Falta documentar.

2019-08-28 02:43 UTC, didierrenardub commented on resources/templates/EditEmployee.html
> +    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
Podrían usar SASS, LESS o algún preprocesador de css para mejorar la forma en que se manejan las clases. Por ejemplo, en este caso, se podría establecer un id para el `nav` y tener un less como este:

`#edit-employee-nav`
`{`
`    .navbar;`
`   .navbar-expand-lg;`
`   .fixed-top;`
`   .navbar-dark;`
`   .bg-dark;`
`}`

2019-08-28 02:43 UTC, didierrenardub commented on resources/templates/ErrorPage.html
> +    <script th:inline="javascript">
Esto debería ir a parar a un js.

2019-08-28 02:43 UTC, didierrenardub commented on resources/templates/ManagerClients.html
> +                <td style="vertical-align: inherit;" th:text="${client.getFullName()}"></td>
Evitar la presencia del atributo style. Definir y utilizar clases css. Sucede en la línea de arriba, y más arriba al abrir la tabla y el div que la contiene.

2019-08-28 02:43 UTC, didierrenardub commented on resources/templates/EditEmployee.html
> +        <a class="navbar-brand" href="/admin_main">Administrador</a>
No se los voy a requerir para este trabajo, pero siendo que utilizan un motor como Spring, todo lo que sea texto dentro de la página tiene que estar referido por medio de constantes y utilizando la facilidad del framework para localización. Esto permite que el día de mañana, de necesitarse traducir el sitio, sea una tarea mucho más sencilla.

2019-08-28 02:43 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/controller/ErrorController.java
> +    @GetMapping("/errorpage")
Inconsistencia en el mapping: por ejemplo, en src/ar/edu/ub/progiii/mvc/controller/DashboardController.java se lee:
`@GetMapping("/Admin")`
Es decir, comienza en mayúscula, y no sucede lo mismo con el caso actual de `errorpage`.

2019-08-28 02:43 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/controller/LoginController.java
> +		if(aux) {
Podría utilizarse directamente la condición, sin necesidad de definir aux.

2019-08-28 02:43 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/controller/ManagerController.java
> +            RedirectView redirectView = new RedirectView("/manage_employees");
Estas 3 líneas de código se repiten demasiado en los métodos de esta clase y todavía no vi se se utiliza en otra. Habría que definir un método que lo encapsule.

2019-08-28 02:43 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/controller/TicketsController.java
> +        if(result == 1)return new ModelAndView(redirectView);
Evitar el uso de if sin las llaves.

2019-08-28 02:43 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/controller/DashboardController.java
> +    @GetMapping("/Admin")
Lo menciono una vez para no spammear, pero falta la documentación en todos los métodos y definiciones de clases de todos los controllers que vi hasta ahora.

2019-08-28 02:43 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/dto/ClientDTO.java
>  	 * @param ClientNumber representa el numero de cliente.
Inconsistencia en el casing de las variables.

2019-08-28 02:43 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/dto/TicketDTO.java
> +    public TicketDTO(String ticketTitle, String ticketAuthor, String ticketContent,String ID,String Date,String Status) {
Inconsistencia en el casing de los parámetros.

2019-08-28 02:43 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/repository/Data.java
> +        String SPsql = "EXEC GenerarLog '"+Tipo+"' , '"+Mensaje+"' ";
En línea con lo que dije en otro lugar de la review, hay que poner las consultas SQL en algún otro lugar para su más fácil manipulación, mantenimiento, etc..

2019-08-28 02:43 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/repository/Data.java
> +            System.out.println("El numero ingresado no es valido");
Utilizar LogData en lugar de System.ou.println, siendo que se definió el método.

2019-08-28 02:43 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/repository/Data.java
> +                     result += (rst.getString("NombreCompleto"))+"_";
Este código se repite muchísimo en estos archivos. Definir un método para encapsularlo de manera tal que se reutilice.

2019-08-28 02:43 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/repository/Data.java
> +    public String GetClientByUId(String data) {
En sí, la estructura de todos estos métodos es la misma, sólo cambian la query y los resultados. Busquen la forma de reutilizar la mayor parte de la estructura.

2019-08-28 02:43 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/service/ClientService.java
> +        return response;
Podría estar todo directamente en la misma línea:
`return dataManager.PostNewClient(clientDTO);`

2019-08-28 02:43 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/service/ClientService.java
> +            if(item.getEmployeeNumber() == EmployeeNumber)return item;
Evitar if sin llaves.

2019-08-28 02:43 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/tests/blank.java
> +public class blank {
Esta clase pareciera estar de más...

2019-08-28 12:58 UTC, federicofranco97 commented on .gitignore
> +.idea
Buenas! Con eso tengo dudas, revise todas las branches y esta el .idea incluido, pero alguna branch capaz ya lo tenia en el repositorio remoto asi que vamos a tener que borrar la carpeta idea, pushear y ahi si quedamos bien

2019-08-28 13:01 UTC, federicofranco97 commented on codeSqlServer/Conection.java
>  			ResultSet rst = stm.executeQuery("select * from dbo.Cliente");
Perdon! Ese codigo lo habia pasado diego de como hacer la conexion pero esa carpeta no deberia estar en el proyecto! Hoy la eliminamos

2019-08-28 13:02 UTC, federicofranco97 commented
Ahora, como hacemos con los cambios? Cerramos el pr, hacemos las modificaciones y lo mandamos de nuevo? O con modificar en el codigo y pushear alcanza?

2019-08-28 13:06 UTC, didierrenardub commented
No, el PR lo dejan abierto. Cada vez que se pushean commits al branch de
origen del PR, el mismo se actualiza automáticamente.

Lo correcto sería que cada uno trabaje en el branch que corresponde a cada
cambio que haya que hacer en base a las tareas a las que pertenecen, luego
hacer PR de esos branches a rejunte y, al mergear, el PR de rejunte a
master_dev se va a actualizar automáticamente. Cuando tienen todo listo me
avisan y veo los cambios de esos commits arreglando los comentarios que
puse.

Saludos!

El mié., 28 ago. 2019 a las 10:02, Federico Franco (<
notifications@github.com>) escribió:

> Ahora, como hacemos con los cambios? Cerramos el pr, hacemos las
> modificaciones y lo mandamos de nuevo? O con modificar en el codigo y
> pushear alcanza?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/federicofranco97/ProyectoCine/pull/32?email_source=notifications&email_token=AE7FCFK7Z27I7EUKIZ245BDQGZZP3A5CNFSM4IQOUYWKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5LBJPI#issuecomment-525735101>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AE7FCFPWVG62X5SUMSQLCHTQGZZP3ANCNFSM4IQOUYWA>
> .
>

2019-08-28 13:08 UTC, federicofranco97 commented on src/ar/edu/ub/progiii/mvc/repository/Data.java
> +                     result += (rst.getString("NombreCompleto"))+"_";
En esto tengo dudas de como, si se repite pero es porque cada query es distinta con otros parametros y devuelve resultados con cantidad de columnas distinto. Y hay que pedir especificamente por el nombre de columna para que quede ordenado. Se me ocurre un metodo que le pasemos la query y  un array de strings que sean los nombres de las columnas pero no lo veo muy prolijo. Por eso lo pusimos asi que se entiende mejor por mas que sea medio repetitivo

2019-08-28 13:41 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/repository/Data.java
> +                     result += (rst.getString("NombreCompleto"))+"_";
Lo de la prolijidad se puede discutir, es más bien subjetivo... pero desde el punto de vista de reusabilidad no hay excusas; haciendo una clase se podría resolver lo que vos decís, de todos modos. Por ejemplo:

```java
class QueryRunner
{
    public QueryRunner(Connection conn, String queryStr)
    {
        this.connection = conn;
        this.queryString = queryStr;
        this.readColumns = null;
    }

    public QueryRunner(Connection conn, String queryStr, String[] readColumns)
    {
        this(conn, queryStr);
        this.readColumns = new ArrayList<>(Arrays.asList(readColumns));
    }
    
    public String run()
    {
        if(this.connection != null)
        {
            try
            {
                return this.readResults(connection.createStatement().executeQuery(this.queryString));
            }
            catch(Exception ex)
            {
                System.out.println("DataException Ocurrio una excepcion al procesar el pedido*** " + ex.getMessage());
            }
        }
        else
        {
            System.out.println("ConError No se pudo conectar con el sql server");
        }

        return null;
    }

    public String readResults(ResultSet rst)
    {
        StringBuilder result = new StringBuilder();
        if(this.readColumns != null)
        {
            for(String column : this.readColumns)
            {
                result.append(rst.getString(column))
                if(column != this.readColumns.get(this.readColumns.size() - 1))
                {
                    result.append("_");
                }
            }
        }
        return result.toString();
    }

    private Connection connection;
    private String queryString;
    private ArrayList<String> readColumns;
}
```

Y en caso de necesitar una lectura más específica de las columnas (para los casos en los que hay datos no-string) heredás y pisás el método readResults de acuerdo a la necesidad.

También podés hacer una versión para las queries que son por id:

```java
class QueryRunnerId extends QueryRunner
{
    public QueryRunnerId(Connection conn, String table, String idColumn, String idValue)
    {
        super(conn, "select * from " + table + " where " + idColumn + "=" + Integer.parseInt(idValue));
    }
}
```

Y así sucesivamente.

2019-08-28 13:51 UTC, federicofranco97 commented
Perfecto! Los PR que hacemos individualmente para corregir las cosas, tambien te ponemos como referente o hacemos como nos venimos manejando de mergear nosotros por pr?

2019-08-28 13:55 UTC, didierrenardub commented
No, siendo que están pasando por rejunte, mándenlos ahí sin mi intervención.

Ojo, en el futuro sería aún más ideal si el flow fuera:
feature-branch > rejunte
feature-branch -> master_dev
feature-branch -> master

Entonces ustedes tendrían rejunte para probar las integraciones; una vez arreglados los problemas, en lugar de hacer PR de rejunte a master_dev hacen del feature-branch a master_dev. Eso haría que sean PRs más atómicos para que los revise.

Saludos!

2019-09-02 23:48 UTC, federicofranco97 commented
Buenas! Si perdon se me escapo a mi ese, hice el metodo para parsear los resultset, por cantidad de conlumnas y atras comitie el metodo que parsea por nombre de columna por eso le agregue eso como extra. 
Los proximos van a seguir con el formato correcto.
Saludos!

2019-09-02 23:50 UTC, didierrenardub commented
E incluso Diego estuvo committeando en inglés, tendrían que ponerse de
acuerdo con qué idioma usar!

Saludos,
Didier

El lun., 2 sept. 2019 a las 20:48, Federico Franco (<
notifications@github.com>) escribió:

> Buenas! Si perdon se me escapo a mi ese, hice el metodo para parsear los
> resultset, por cantidad de conlumnas y atras comitie el metodo que parsea
> por nombre de columna por eso le agregue eso como extra.
> Los proximos van a seguir con el formato correcto.
> Saludos!
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/federicofranco97/ProyectoCine/pull/32?email_source=notifications&email_token=AE7FCFMVQ4SNF26ZRDQWQJLQHWQ6HA5CNFSM4IQOUYWKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5WVJ6Q#issuecomment-527258874>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AE7FCFLYQU7WDBOT4QPDO7LQHWQ6HANCNFSM4IQOUYWA>
> .
>

2019-09-06 22:56 UTC, didierrenardub commented on resources/static/css/Login.css
> +.form-group
No se deja espacio entre las definiciones de las clases CSS; no es consistente con otros archivos en los que se deja espacio en estas situaciones.

2019-09-06 23:51 UTC, didierrenardub requested changes

2019-09-06 23:51 UTC, didierrenardub commented on resources/static/css/ManagerEmp.css
> +    height: 70%;
Se deja un espacio en la asingación de la propiedad cuando en el resto del archivo no; es inconsistente además con otros archivos css.

2019-09-06 23:51 UTC, didierrenardub commented on resources/static/css/Menu.css
> +th, td
No hay espacio entre las definiciones, y las clases de th y td contiene un espaciado extra entre las propiedades no presente en el resto de las clases css.

2019-09-06 23:51 UTC, didierrenardub commented on resources/static/css/Menu.css
> +a{
Llave de apertura de definición de la clase al mismo nivel que el nombre de la misma, no es consistente con el resto de las declaraciones.

2019-09-06 23:51 UTC, didierrenardub commented on resources/static/css/RedeemTickets.css
> +#tableDesign
Falta espaciado entre las clases para mantener coherencia con el resto de las declaraciones.

2019-09-06 23:51 UTC, didierrenardub commented on resources/static/css/Tickets.css
> +     overflow-y: auto;
Espacio extra en la asignación de la propiedad no presente en el resto de las asignaciones.

2019-09-06 23:51 UTC, didierrenardub commented on resources/static/js/Login.js
> +	{
La llave del for y del if de adentro están en una nueva línea, mientras que en function(event) está en la misma línea.
Recuerden mantener la coherencia.

2019-09-06 23:51 UTC, didierrenardub commented on resources/static/js/ManagerClie.js
> +            setTimeout(function(){ window.open("/ban_client?clientid="+idCliente,"_self"); }, 2000);
Definición de función e implementación en el mismo renglón.

2019-09-06 23:51 UTC, didierrenardub commented on resources/static/js/ManagerClie.js
> +        setTimeout(function(){ window.open("/delete_client?clientid="+idCliente,"_self"); }, 1000);
Nuevamente, definición e implementación en la misma línea.

2019-09-06 23:51 UTC, didierrenardub commented on resources/static/js/ManagerClie.js
> +//Te devuelve al menu cliente
Falta un espacio entre el cierre de la función anterior y el comentario.

2019-09-06 23:51 UTC, didierrenardub commented on resources/static/js/ManagerEmp.js
> +    window.open("/edit_employee?employeeid="+idEmployee,"_self");
Se repite mucho la estructura:
/llamada_de_api?employeeid="+idEmployee.

Se podría definir una función que englobe todo el window.open para reutilizar.

2019-09-06 23:51 UTC, didierrenardub commented on resources/static/js/ManagerEmp.js
> +            setTimeout(function(){ window.open("/ban_employee?employeeid="+idEmployee,"_self"); }, 2000);
Definición e implementación en una sola línea.

2019-09-06 23:51 UTC, didierrenardub commented on resources/static/js/ManagerEmp.js
> +        setTimeout(function(){ window.open("/delete_employee?employeeid="+idEmployee,"_self"); }, 2000);
Definición e implementación en la misma línea.

2019-09-06 23:51 UTC, didierrenardub commented on resources/static/js/RedeemTickets.js
> +function BringBooking(){
Falta documentación de la función.

2019-09-06 23:51 UTC, didierrenardub commented on resources/static/js/Withdraw.js
> +var inTotal = document.getElementById("totalSales");
Variables inAmount e inTotal arrancan en minúscula, al contrario del resto de las variables.

2019-09-06 23:51 UTC, didierrenardub commented on resources/static/js/Withdraw.js
> +    if(AmountSelected < 1 || AmountSelected>TotalSales || AmountSelected===null || Number.isNaN(AmountSelected)){
Hay espacios en la primer condición (`AmountSelected < 1`) mientras que en las otras no (por ejemplo, `AmountSelected>TotalSales`)

2019-09-06 23:51 UTC, didierrenardub commented on resources/templates/EditEmployee.html
> +            <label>Fehca de nacimiento</label>
Guarda que dice Fehca de nacimiento "Café de nacimiento" jaja

2019-09-06 23:51 UTC, didierrenardub commented on resources/templates/EditEmployee.html
> +            <label >Address</label>
Hay un espacio extra en el tag de apertura del label

2019-09-06 23:51 UTC, didierrenardub commented on resources/templates/ManagerEmployees.html
> +    <div style="max-height:80vh;overflow-y:auto">
Evitar estilos inline.

2019-09-06 23:51 UTC, didierrenardub commented on resources/templates/ManagerEmployees.html
> +                <td style="vertical-align: inherit;" th:text="${empleado.getFullName()}"></td>
Idem, evitar estilos inline, y más en casos como este que se repite.

2019-09-06 23:51 UTC, didierrenardub commented on resources/templates/Menu.html
> +	<tr>
Las indentaciones en este html no son coherentes respecto de los otros html.

2019-09-06 23:51 UTC, didierrenardub commented on resources/templates/RedeemTickets.html
> +        <h4 style="margin: auto; text-align: center; font-size: 50px">Retiro de entradas</h4>
Evitar estilo inline.

2019-09-06 23:51 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/dto/FilmDTO.java
> +    public String getFilmName() {
Falta documentar getters y setters.

2019-09-06 23:51 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/dto/PersonDTO.java
> +	public void setPhoneNumber(String phoneNumber) {
Falta documentación en los getters y setters.

2019-09-06 23:51 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/dto/TicketDTO.java
> +    public TicketDTO(String ticketTitle, String ticketAuthor, String ticketContent,String ID,String Date,String Status) {
Además hay inconsistencia en los espacios antes y después de las comas.

2019-09-06 23:51 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/model/Client.java
> +	public Client(String fullName, String address, String phoneNumber, String email, String dateOfBirth,int ClientNumber) {
Inconsistencia en los espacios entre parámetros.

2019-09-06 23:51 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/model/Client.java
>  	 * @param dateOfBirth representa la fecha de nacimiento del cliente.
Inconsistencia en el casing de la variables.

2019-09-06 23:51 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/model/Employee.java
> +	public Employee(String fullName, String address, String phoneNumber, String email, String dateOfBirth,int EmployeeNumber,
Inconsistencia en el casing de las variables y los espacios entre parámetros.

2019-09-06 23:51 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/model/Person.java
> +	public void setFullName(String fullName) {
Falta documentación getters y setters.

2019-09-06 23:51 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/repository/Connection.java
> +    public static java.sql.Connection getConnection() {
Falta documentar la clase.

2019-09-06 23:51 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/repository/Data.java
> +            for (int i = 1; i < ParameterAmount; i++) {
Inconsistencia en el espacio entre la llave y el final de la instrucción anterior en este archivo. Por ejemplo, el while de arriba no deja espacio y este sí.

2019-09-06 23:51 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/repository/querys/CQuerySelect.java
> +        StatementConditions = statementConditions;
Falta documentar esta clase.

2019-09-06 23:51 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/repository/querys/CQueryUpdate.java
> +    public ArrayList<String> getStatementConditions() {
Falta documentar estos métodos.

2019-09-06 23:51 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/repository/querys/ConditionQueryBuilder.java
> +    public abstract ArrayList<String> getStatementConditions();
Falta documentar la clase.

2019-09-06 23:51 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/repository/querys/QueryInsert.java
> +	public static ArrayList<String> getColumns() {
Falta documentar todos estos métodos.

2019-09-06 23:51 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/repository/querys/QueryStoredProcedure.java
> +    public void addParameter(List<String> parameters){
Falta documentar la clase.

2019-09-06 23:51 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/repository/querys/QueryStoredProcedureWResponse.java
> +    public void addParameter(List<String> parameters){
Falta documentar la clase.

2019-09-06 23:51 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/service/ClientService.java
> +        return dataManager.GetEployeesActive();
Falta documentar varios de estos métodos.

2019-09-13 22:46 UTC, diegomoran31 commented on codeSqlServer/Conection.java
> +				System.out.println("nombre: " + rst.getString("NombreCompleto"));
ya no existe esta clase

2019-09-14 00:50 UTC, beelanselm commented on resources/static/js/ManagerEmp.js
> +    window.open("/edit_employee?employeeid="+idEmployee,"_self");
Esto acordamos verbalmente no modificarlo

2019-09-15 04:14 UTC, diegomoran31 commented on src/ar/edu/ub/progiii/mvc/repository/Data.java
> +            System.out.println("El numero ingresado no es valido");
En algunos es para uso interno ya que por ejemplo en el caso que marcas  todavia no conecto a la bse de datos , por lo tanto no va a guardar el log, inclusive ya da retorno nulo y no permite conectar si pasara esto..

2019-09-16 18:29 UTC, didierrenardub commented on resources/static/js/ManagerClie.js
> +function MoveToDelete(){
Falta un espacio de separación entre los métodos, y tiene el nombre duplicado por lo cual va a haber problemas a la hora de ejecutarlo.

2019-09-16 18:35 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/controller/ErrorController.java
> +    @GetMapping("/errorpage")
La conversación se había marcado como resuelta pero este problema no se resolvió.

2019-09-16 18:36 UTC, didierrenardub commented on resources/templates/ManagerEmployees.html
> +                <td style="vertical-align: inherit;" th:text="${empleado.getFullName()}"></td>
Conversación marcada como resuelta cuando el problema sigue ahí.

2019-09-16 18:37 UTC, didierrenardub commented on src/ar/edu/ub/progiii/mvc/controller/ManagerController.java
> +            RedirectView redirectView = new RedirectView("/manage_employees");
No fue resuelto.

2019-09-16 18:41 UTC, didierrenardub approved these changes
Apruebo porque no puedo seguir revisando tanto código junto, pero hubo comentarios marcados como resueltos que no fueron arreglados y deberían.

Es importante que aprueben la materia y terminen la carrera, sí, pero no sirve de nada si no se convierten en buenos profesionales. Las cosas que les digo no son por capricho o por estar aburrido y no tener nada mejor que hacer, sino porque son buenas prácticas que los va a ayudar a convertirse en programadores destacados.

Saludos!

2019-09-16 18:45 UTC, diegomoran31 commented
No tengo duda de eso..y trataremos de resolver lo marcado...
No vamos a dejar todo asi nomas..no te preocupes.

El lun., 16 sept. 2019 15:41, Didier Renard <notifications@github.com>
escribió:

> *@didierrenardub* approved this pull request.
>
> Apruebo porque no puedo seguir revisando tanto código junto, pero hubo
> comentarios marcados como resueltos que no fueron arreglados y deberían.
>
> Es importante que aprueben la materia y terminen la carrera, sí, pero no
> sirve de nada si no se convierten en buenos profesionales. Las cosas que
> les digo no son por capricho o por estar aburrido y no tener nada mejor que
> hacer, sino porque son buenas prácticas que los va a ayudar a convertirse
> en programadores destacados.
>
> Saludos!
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/federicofranco97/ProyectoCine/pull/32?email_source=notifications&email_token=AMZY3VT4D6YHTZVT5PCXQQTQJ7HL3A5CNFSM4IQOUYWKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCE3RYGI#pullrequestreview-288824345>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMZY3VQDGYVHH4275IOLAHDQJ7HL3ANCNFSM4IQOUYWA>
> .
>

2019-09-16 19:54 UTC, diegomoran31 commented on src/ar/edu/ub/progiii/mvc/controller/ErrorController.java
> +    @GetMapping("/errorpage")
es que en dashboard ya se puso asi con  minuscula
@GetMapping("/admin")

2019-09-16 19:55 UTC, diegomoran31 commented on src/ar/edu/ub/progiii/mvc/controller/ManagerController.java
> +            RedirectView redirectView = new RedirectView("/manage_employees");
en este caso sacamos el result y pusimos todo dentro de la condicion 
por ej:
@GetMapping("/delete_employee")
    public ModelAndView DeleteEmployee(@RequestParam("employeeid")int EmployeeNumber){
        if(clientService.DeleteEmployee(EmployeeNumber) == 1 ){
            RedirectView redirectView = new RedirectView("/manage_employees");

2019-09-16 19:57 UTC, diegomoran31 commented on resources/templates/ManagerEmployees.html
> +                <td style="vertical-align: inherit;" th:text="${empleado.getFullName()}"></td>
ahora veo de arreglar esto pero te comento que habiamos quedado con vs en que no se cambiaba en el caso de que estuviera bootstrap en medio

2019-09-16 19:59 UTC, didierrenardub commented on resources/templates/ManagerEmployees.html
> +                <td style="vertical-align: inherit;" th:text="${empleado.getFullName()}"></td>
En clase habíamos visto que el problema no era bootstrap sino la caché del browser. Me parece que fue después de que te fuiste...

2019-09-16 20:00 UTC, diegomoran31 commented on resources/static/js/ManagerClie.js
> +function MoveToDelete(){
El espacio lo acabo de arreglar..
En cuanto al duplicado de moveToDelete :
function MoveToDelete() solo esta definiendo la funcion..
mas arriba dentro del swal solamente se esta utilizando..
no es que este repetida en este caso..

2019-09-16 20:05 UTC, didierrenardub commented on resources/static/js/ManagerClie.js
> +function MoveToDelete(){
Está definido en:
resources/static/js/ManagerClie.js:31
```
function MoveToDelete(){
    window.open("/ban_client?clientid="+idCliente,"_self");
    }
```

Y luego:
resources/static/js/ManagerClie.js:57
```
function MoveToDelete(){
    window.open("/delete_client?clientid="+idCliente,"_self");
}
```

La url que intenta abrir es distinta...

2019-09-16 20:22 UTC, diegomoran31 commented
ahi lo vi, ya lo cambio, tenes toda la razon.....hay que ponerle un
paramatro a la funcion..

El lun., 16 sept. 2019 a las 17:05, Didier Renard (<notifications@github.com>)
escribió:

> *@didierrenardub* commented on this pull request.
> ------------------------------
>
> In resources/static/js/ManagerClie.js
> <https://github.com/federicofranco97/ProyectoCine/pull/32#discussion_r324861290>
> :
>
> > +      dangerMode: true,
>
> +    })
>
> +    .then((willDelete) => {
>
> +      if (willDelete) {
>
> +        swal("Cliente eliminado!", {
>
> +          icon: "success",
>
> +        });
>
> +        setTimeout("MoveToDelete()", 1000);
>
> +      } else {
>
> +        swal("Accion Revertida!", {
>
> +            icon: "success",
>
> +        });
>
> +      }
>
> +    });
>
> +}
>
> +function MoveToDelete(){
>
>
> Está definido en:
> resources/static/js/ManagerClie.js:31
>
> function MoveToDelete(){
>
>     window.open("/ban_client?clientid="+idCliente,"_self");
>
>     }
>
>
> Y luego:
> resources/static/js/ManagerClie.js:57
>
> function MoveToDelete(){
>
>     window.open("/delete_client?clientid="+idCliente,"_self");
>
> }
>
>
> La url que intenta abrir es distinta...
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/federicofranco97/ProyectoCine/pull/32?email_source=notifications&email_token=AMZY3VWO66YM377TRSZL5NTQJ7RJRA5CNFSM4IQOUYWKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCE34S2I#discussion_r324861290>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AMZY3VQLGJ7AJUSKGZOPUL3QJ7RJRANCNFSM4IQOUYWA>
> .
>

2019-09-19 23:55 UTC, merged